stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/a1_RestaurantReviews_HistoricDump.tsv
    outs:
      - artifacts/preprocessed_data.pkl
      - artifacts/c1_BoW_Sentiment_Model.pkl

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - artifacts/preprocessed_data.pkl
      - params.yaml
    params:
      - train.random_state
      - train.grid_search.n_estimators
      - train.grid_search.max_depth
      - train.cross_validation
    outs:
      - artifacts/trained_model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - artifacts/trained_model.pkl
      - artifacts/preprocessed_data.pkl
    outs:
      - artifacts/sentiment_model.pkl
    metrics:
      - artifacts/metrics.json:
          cache: false