name: Train and Release Model

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install git+https://github.com/remla25-team21/lib-ml.git@v0.0.6
          pip install -r requirements.txt

      - name: Train the model
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: python train_model.py

      - name: Create release (if not already created)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release upload URL
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.ref.split("/").pop();
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag,
            });
            core.setOutput("upload_url", release.data.upload_url);

      - name: Upload trained model
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./artifacts/sentiment_model_${{ github.ref_name }}.pkl
          asset_name: sentiment_model_${{ github.ref_name }}.pkl
          asset_content_type: application/octet-stream

      - name: Upload vectorizer
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./artifacts/c1_BoW_Sentiment_Model_${{ github.ref_name }}.pkl
          asset_name: c1_BoW_Sentiment_Model_${{ github.ref_name }}.pkl
          asset_content_type: application/octet-stream
